name: Deploy Frontend to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy frontend to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: frontendfullstack
          slot-name: production
          publish-profile: ${{ secrets.AZURE_FRONTEND_PUBLISH_PROFILE }}
          package: ./frontend
